export default [
  {
    icon: 'list-check-icon',
    title: 'Referensi',
    children: [
      {
        icon: 'hand-click-icon',
        title: 'Periodik',
        route: 'referensi-periodik',
        resource: 'Ref_Periodik',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Sekolah',
        route: 'referensi-sekolah',
        resource: 'Ref_Sekolah',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Guru',
        route: 'referensi-guru',
        resource: 'Ref_Guru',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Peserta Didik',
        route: 'referensi-peserta-didik',
        resource: 'Ref_Pd',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Jurusan',
        route: 'referensi-jurusan',
        resource: 'Ref_Jurusan',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Mata Pelajaran',
        route: 'referensi-mata-pelajaran',
        resource: 'Ref_Mapel',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Kelompok Mapel',
        route: 'referensi-kelompok-mapel',
        resource: 'System',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Kelas',
        route: 'referensi-kelas',
        resource: 'Ref_Kelas',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Ekstrakurikuler',
        route: 'referensi-ekstrakurikuler',
        resource: 'System',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Mapping Guru BK',
        route: 'guru-bk',
        resource: 'Guru_BK',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Capaian Pembelajaran',
        route: 'referensi-capaian-pembelajaran',
        resource: 'System',
        action: 'read',
      },
      {
        icon: 'hand-click-icon',
        title: 'Bahan Ajar',
        route: 'referensi-bahan-ajar',
        action: 'read',
        resource: 'Modul',
      },
    ],
  },
]
  